- name: Deploy archive-api service
  community.docker.docker_container:
    name: dds-archive-api
    image: "{{ registry }}/{{ registry_path }}/{{ services['dds-archive-api'].image }}:{{ rollback_image_tag | default(image_tag) }}"
    ports:
      - "8990:8990"
    env:
      LISTEN_HOST: 0.0.0.0
      LISTEN_PORT: "8990"

      DB_PG_NAME: archive
      DB_PG_USER: archive
      DB_PG_PASS: password
      DB_PG_HOST: "host"
      DB_PG_PORT: "5432"

      LOG_LEVEL: "{{ log_level }}"
      PROJECT_ENV: "{{ env }}"
    etc_hosts:
      host: host-gateway
    restart_policy: always
    pull: "{{ online | ternary('always', 'never') }}"
  tags:
    - dds-archive-api
