- name: Get host IPs
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - all_ipv4_addresses
  tags:
    - dds-camera-video

- name: Deploy camera-video service
  community.docker.docker_container:
    name: dds-camera-video
    image: "{{ registry }}/{{ registry_path }}/{{ services['dds-camera-video'].image }}:{{ rollback_image_tag | default(image_tag) }}"
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/tcp"
      - "8890:8890/udp"
      - "8189:8189/tcp"
      - "8189:8189/udp"
    env:
      MTX_WEBRTCADDITIONALHOSTS: "{{ ansible_all_ipv4_addresses | join(',') }}"
    env_file: "{{ data_root }}/configs/devices.env"
    restart_policy: always
    pull: "{{ online | ternary('always', 'never') }}"
    comparisons:
      env: strict
    state: "{{ video_devices_present | ternary('started', 'stopped') }}"
  tags:
    - dds-camera-video
