- name: Deploy control-proxy service
  community.docker.docker_container:
    name: dds-control-proxy
    image: "{{ registry }}/{{ registry_path }}/{{ services['dds-control-proxy'].image }}:{{ rollback_image_tag | default(image_tag) }}"
    ports:
      - "8080:8080"
    env:
      LISTEN_UPLOAD: "8080"
      LISTEN_PORT: "8081"
      UPLOAD_DIR: /var/upload
      BACKUPS_DIR: /var/backups
      APP_ID: dds-control-proxy
      PROJECT_ENV: "{{ env }}"
    etc_hosts:
      host: host-gateway
    volumes:
      - "{{ data_root }}/control/upload:/var/upload"
      - "{{ data_root }}/backups:/var/backups"
    restart_policy: always
    pull: "{{ online | ternary('always', 'never') }}"
#    recreate: true
  tags:
    - dds-control-proxy
