- name: Deploy postgres service
  community.docker.docker_container:
    name: dds-infra-postgres
    image: "{{ registry }}/{{ registry_path }}/{{ services['dds-infra-postgres'].image }}:{{ rollback_image_tag | default(image_tag) }}"
    ports:
      - "5432:5432"
    env:
      POSTGRES_PASSWORD: "{{ db.postgres.password }}"
    volumes:
      - "{{ paths.data_root_host }}/infra/postgres:/var/lib/postgresql/data"
    restart_policy: always
    pull: "{{ online | ternary('always', 'never') }}"
#    recreate: true
  tags:
    - dds-infra-postgres

- name: Waiting for postgres is ready
  community.docker.docker_container_info:
    name: "dds-infra-postgres"
  register: container_info
  until: "container_info.container.State.Health.Status == 'healthy'"
  retries: 10
  delay: 5
  tags:
    - dds-infra-postgres

- name: Create postgres users
  community.postgresql.postgresql_user:
    name: "{{ item }}"
    password: "{{ db.postgres.password }}"

    login_host: localhost
    login_password: "{{ db.postgres.password }}"
  loop: "{{ db.postgres.databases }}"
  tags:
    - dds-infra-postgres

- name: Create postgres databases
  community.postgresql.postgresql_db:
    name: "{{ item }}"
    owner: "{{ item }}"

    login_host: localhost
    login_password: "{{ db.postgres.password }}"
  loop: "{{ db.postgres.databases }}"
  tags:
    - dds-infra-postgres
