- name: Deploy node-exporter service
  community.docker.docker_container:
    name: dds-infra-node-exporter
    image: "{{ registry }}/{{ registry_path }}/{{ services['dds-infra-node-exporter'].image }}:{{ rollback_image_tag | default(image_tag) }}"
    ports:
      - "9100:9100"
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    restart_policy: always
    pull: "{{ online | ternary('always', 'never') }}"
#    recreate: true
  tags:
    - dds-infra-node-exporter
