- name: Get firmware images files
  find:
    paths: "{{ data_root }}/control/firmware"
    patterns: "*.tar"
  register: images

- name: Load firmware images
  community.docker.docker_image_load:
    path: "{{ item }}"
    timeout: 200
  loop: "{{ images.files | map(attribute='path') | list }}"

- name: Read firmware info file
  slurp:
    src: "{{ data_root }}/control/firmware/metadata.yaml"
  register: firmware

- name: Get firmware info
  set_fact:
    firmware: '{{ firmware.content | b64decode | from_yaml }}'
