- name: Deploy ui service
  community.docker.docker_container:
    name: dds-ui
    image: "{{ registry }}/{{ registry_path }}/{{ services['dds-ui'].image }}:{{ rollback_image_tag | default(image_tag) }}"
    env:
      LISTEN: "80"

      DB_PG_NAME: proto
      DB_PG_USER: proto
      DB_PG_PASS: password
      DB_PG_HOST: "host"
      DB_PG_PORT: "5432"
    ports:
      - "80:80"
    etc_hosts:
      host: host-gateway
    volumes:
      - "{{ paths.data_root_host }}/ui/db_data:/mam/mpk/dse/dist/-/.crus"
      - "{{ paths.data_root_host }}/ui/db_key:/root/.local/share/mol_state_local"
    restart_policy: always
    recreate: true
    pull: "{{ online | ternary('always', 'never') }}"
  tags:
    - dds-ui
