version: v2beta1
name: dds-provider

imports:
- path: devspace.local-env.yaml
- path: configs/dev/env.yaml

images:
  app:
    image: ${CI_REGISTRY_IMAGE}
    buildArgs:
      VERSION: ${VERSION}
      APP_ID: dds-provider
      GO_VER: ${GO_VER}
      GOMOD_TOKEN: ${GOMOD_TOKEN}
      GOMOD_HOST: ${CI_SERVER_HOST}
    buildKit:
      args: [
        "--platform=${PLATFORMS}",
        "--cache-from=type=registry,ref=${CI_REGISTRY_IMAGE}/buildcache:${BUILDER_TAG}",
        "--cache-from=type=registry,ref=${CI_REGISTRY_IMAGE}/buildcache:${IMAGE_TAG}",
      ]

pipelines:
  build: |-
    build_images ${@:---all} -t $IMAGE_TAG

  deploy: |-
    export "$@"
    docker compose --env-file $DEVSPACE_ENV_FILE up -d


commands:
  logs: |-
    docker compose logs -f "$@"

  dev: |-
    # Check we are not in dev container
    [ ! -d /workspace ] && devspace purge || true
    
    while [ -n "$1" ]; do
      [ "$1" = "--" ] && break
      export "$1"
      shift
    done
    shift
    . configs/dev/set_profiles_defaults.sh
    go run main.go -debug "$@"

  format: |-
    CI_SERVER_HOST= devspace --silent run format_cxx src "$@"

  lint: |-
    export CI_SERVER_HOST=
    devspace --silent run lint_spell . "$@"
    #devspace --silent run lint_cxx ${CI_REGISTRY_IMAGE}/intel/dss-ubuntu-builder:current src "$@"
    #devspace --silent run lint_cxx_qt ${CI_REGISTRY_IMAGE}/intel/dss-ubuntu-builder:current src "$@"

  validate: |-
    export CI_SERVER_HOST=
    devspace --silent run run-tools-cmd lint_proto api/proto
    devspace --silent run lint_openapi api/bulat-openapi.yaml

  gen: |-
    export CI_SERVER_HOST=
    devspace run tool-gen go_connectrpc_server api/proto internal/generated dds-provider
    devspace run tool-gen go_openapi_client ../dds-target-provider/docs/api/dss-target-service-schema.yaml \
      internal/generated/provider_client \
      provider_client
    devspace run tool-gen go_openapi_client api/external/bulat-openapi.yaml internal/generated/bulat api

  buf: |-
    export PATH="$(go env GOPATH)/bin:$PATH"
    which buf > /dev/null || CI_SERVER_HOST= devspace --silent run run-tools-cmd install_go_tools
    buf "$@"

  clean: |-
    docker builder prune --filter type=exec.cachemount -f

profiles:
  - name: bulat
  - name: ci
    activation:
      - env:
          CI_JOB_ID: "\\d+"
    patches:
      - op: add
        path: images.app.buildKit.args
        value: "--cache-to=type=registry,ref=${CI_REGISTRY_IMAGE}/buildcache:${IMAGE_TAG},mode=max,compression=zstd"

