intel/license-ubuntu-builder-images/mr:
  stage: docker-build
  image: registry.dev.mpksoft.ru/mpk/internal/docker-builder:current
  services:
    - $DOCKER_DIND_IMAGE
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - tag="$CI_COMMIT_REF_SLUG"
    - >
        dir="docker/intel/license-ubuntu-builder" &&
        image="${dir#*/}" &&
        docker build --pull --cache-from=${CI_REGISTRY_IMAGE}/${image}:${CI_COMMIT_REF_SLUG} \
          --tag ${CI_REGISTRY_IMAGE}/${image}:${tag} \
          --tag ${CI_REGISTRY_IMAGE}/${image}:latest $dir || exit $? &&
        docker push --quiet ${CI_REGISTRY_IMAGE}/${image}:${tag} &&
        docker push --quiet ${CI_REGISTRY_IMAGE}/${image}:latest
  only:
    refs:
      - merge_requests
    changes:
      - docker/intel/license-ubuntu-builder/*
  tags:
    - docker

intel/license-debian-builder-images/mr:
  stage: docker-build
  image: registry.dev.mpksoft.ru/mpk/internal/docker-builder:current
  services:
    - $DOCKER_DIND_IMAGE
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - tag="$CI_COMMIT_REF_SLUG"
    - >
        dir="docker/intel/license-debian-builder" &&
        image="${dir#*/}" &&
        docker build --pull --cache-from=${CI_REGISTRY_IMAGE}/${image}:${CI_COMMIT_REF_SLUG} \
          --tag ${CI_REGISTRY_IMAGE}/${image}:${tag} \
          --tag ${CI_REGISTRY_IMAGE}/${image}:latest $dir || exit $? &&
        docker push --quiet ${CI_REGISTRY_IMAGE}/${image}:${tag} &&
        docker push --quiet ${CI_REGISTRY_IMAGE}/${image}:latest
  only:
    refs:
      - merge_requests
    changes:
      - docker/intel/license-debian-builder/*
  tags:
    - docker

arm64/license-ubuntu-builder-images/mr:
  stage: docker-build
  image: registry.dev.mpksoft.ru/mpk/internal/docker-builder:current
  services:
    - $DOCKER_DIND_IMAGE
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - tag="$CI_COMMIT_REF_SLUG"
    - >
        dir="docker/arm64/license-ubuntu-builder" &&
        image="${dir#*/}" &&
        docker build --pull --cache-from=${CI_REGISTRY_IMAGE}/${image}:${CI_COMMIT_REF_SLUG} \
          --tag ${CI_REGISTRY_IMAGE}/${image}:${tag} \
          --tag ${CI_REGISTRY_IMAGE}/${image}:latest $dir || exit $? &&
        docker push --quiet ${CI_REGISTRY_IMAGE}/${image}:${tag} &&
        docker push --quiet ${CI_REGISTRY_IMAGE}/${image}:latest
  only:
    refs:
      - merge_requests
    changes:
      - docker/arm64/license-ubuntu-builder/*
  tags:
    - docker
