services:

  app:
    container_name: dds-target-provider
    image: ${CI_REGISTRY_IMAGE}:${IMAGE_TAG}
    environment:
      - LICENSE_FILE=/var/license/dds-provider.lic

      - HTTP_LISTEN
      - WS_LISTEN

      - DB_PG_NAME
      - DB_PG_USER
      - DB_PG_PASS
      - DB_PG_HOST
      - DB_PG_PORT

      - LOG_LEVEL

      - GROUP_JAMMER_DEVICES

      - GENERIC_DEVICES
      - ALIA_DEVICES
      - TAMERLAN_DEVICES
      - RADARIQ_DEVICES
      - SKYCOPE_DEVICES
#    ports: # for documenting purpose only
#      - 19080:19080
#      - 19081:19081
    volumes:
      - ${DATA_ROOT}/license:/var/license:rw
      - /dev:/dev
    # https://stackoverflow.com/questions/24225647/docker-a-way-to-give-access-to-a-host-usb-or-serial-device
    network_mode: host
    device_cgroup_rules:
      - "c 188:* rmw"
    restart: unless-stopped
