<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="ru_RU" sourcelanguage="ru_RU">
<context>
    <name>mpk::metric_units</name>
    <message>
        <source>c</source>
        <translation>с</translation>
    </message>
    <message>
        <source>da</source>
        <translation>да</translation>
    </message>
    <message>
        <source>d</source>
        <translation>д</translation>
    </message>
    <message>
        <source>G</source>
        <translation>Г</translation>
    </message>
    <message>
        <source>h</source>
        <translation>г</translation>
    </message>
    <message>
        <source>k</source>
        <translation>к</translation>
    </message>
    <message>
        <source>M</source>
        <translation>М</translation>
    </message>
    <message>
        <source>u</source>
        <translation>мк</translation>
    </message>
    <message>
        <source>m</source>
        <translation>м</translation>
    </message>
    <message>
        <source>n</source>
        <translation>н</translation>
    </message>
    <message>
        <source>P</source>
        <translation>П</translation>
    </message>
    <message>
        <source>p</source>
        <translation>п</translation>
    </message>
    <message>
        <source>T</source>
        <translation>Т</translation>
    </message>
    <message>
        <source>dB</source>
        <translation>дБ</translation>
    </message>
    <message>
        <source>E</source>
        <translation>Э</translation>
    </message>
    <message>
        <source>f</source>
        <translation>ф</translation>
    </message>
    <message>
        <source>a</source>
        <translation>а</translation>
    </message>
</context>
</TS>
