- name: Install Docker and python adapter
  apt:
    name:
      - docker.io
      - python3-requests
    state: latest
    install_recommends: no

- name: Ensure Docker config directory exists
  file:
    path: /etc/docker
    state: directory

- name: Login to {{ registry }}
  vars:
    creds: "{{ lookup('env', 'REGISTRY_CREDS').split(':') }}"
  community.docker.docker_login:
    username: "{{ creds[0] }}"
    password: "{{ creds[1] }}"
    registry_url: "{{ registry }}"
  when: lookup('env', 'REGISTRY_CREDS') != ''
