openapi: 3.1.0
info:
  title: api.v1
paths: {}
components:
  schemas:
    api.v1.GeoPositionMode:
      type: string
      title: GeoPositionMode
      enum:
        - GEO_POSITION_MODE_AUTO
        - GEO_POSITION_MODE_MANUAL
        - GEO_POSITION_MODE_ALWAYS_MANUAL
    api.v1.GeoCoordinate:
      type: object
      properties:
        latitude:
          exclusiveMaximum: 90
          type: number
          title: latitude
          minimum: -90
          format: double
          description: Latitude in decimal degrees
          nullable: true
        longitude:
          exclusiveMaximum: 180
          type: number
          title: longitude
          minimum: -180
          format: double
          description: Longitude in decimal degrees
          nullable: true
        altitude:
          type: number
          title: altitude
          format: double
          description: Altitude in meters above sea level
          nullable: true
      title: GeoCoordinate
      required:
        - latitude
        - longitude
      additionalProperties: false
    api.v1.GeoPosition:
      type: object
      properties:
        azimuth:
          exclusiveMaximum: 360
          type: number
          title: azimuth
          format: double
          nullable: true
        coordinate:
          title: coordinate
          nullable: true
          $ref: '#/components/schemas/api.v1.GeoCoordinate'
      title: GeoPosition
      required:
        - azimuth
        - coordinate
      additionalProperties: false
    api.v1.HwInfo:
      type: object
      properties:
        temperature:
          type: string
          title: temperature
          nullable: true
        voltage:
          type: string
          title: voltage
          nullable: true
        current:
          type: string
          title: current
          nullable: true
      title: HwInfo
      additionalProperties: false
    api.v1.WorkzoneSector:
      type: object
      properties:
        number:
          type: integer
          title: number
          format: int32
          nullable: true
        distance:
          type: number
          title: distance
          format: double
          nullable: true
        minAngle:
          exclusiveMaximum: 360
          type: number
          title: min_angle
          format: double
          nullable: true
        maxAngle:
          exclusiveMaximum: 360
          type: number
          title: max_angle
          format: double
          nullable: true
      title: WorkzoneSector
      required:
        - number
        - distance
        - minAngle
        - maxAngle
      additionalProperties: false
security: []
