variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: normal
  JOBS_NUMBER: 8
  STATIC_ANALYSIS_IMAGE: ${CI_REGISTRY}/mpk/ci/qt6-static-analysis-image:latest  
  ARCH_IMAGE: ${CI_REGISTRY}/mpk/internal/arch-builder:current
  ASTRA_IMAGE: ${CI_REGISTRY}/mpk/internal/astralinux_1.7-builder:current
  DEB_IMAGE: ${CI_REGISTRY}/mpk/internal/debian-builder:current
  DEB_MXE_IMAGE: ${CI_REGISTRY}/mpk/internal/debian-mxe_shared-builder:current
  CHECK_SUBMODULES: "false"
  CMAKE_ARGS: "-DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_STANDARD=20 \
            -DCMAKE_BUILD_TYPE=Debug \
            -DQT_QMAKE_EXECUTABLE=qmake \
            -DBUILD_EXAMPLES=ON \
            -DBUILD_TESTS=ON"
stages:
  - analysis
  - build

include:
  - project: 'mpk/ci'
    file: '/static-checks.yml'
  - project: 'mpk/ci'
    file: '/static-analysis.yml'

gcc-release-qt6:
  stage: build
  image: ${CI_REGISTRY}/mpk/internal/qt6-alpine-builder:latest
  script:
    - cmake -B.build -GNinja -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Release -DQT_QMAKE_EXECUTABLE=qmake
    - cmake --build .build -j $JOBS_NUMBER
    - pushd .build && ctest --output-on-failure -j $JOBS_NUMBER
  only:
    - merge_requests    
    
gcc-release-arch:
  stage: build
  image: $ARCH_IMAGE
  script:
    - cmake -B.build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Release -DQT_QMAKE_EXECUTABLE=qmake
    - cmake --build .build -j $JOBS_NUMBER
    - pushd .build && ctest --output-on-failure -j $JOBS_NUMBER
  only:
    - merge_requests

gcc-debug-arch:
  stage: build
  image: $ARCH_IMAGE
  script:
    - cmake -B.build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Debug -DQT_QMAKE_EXECUTABLE=qmake
    - cmake --build .build -j $JOBS_NUMBER
    - pushd .build && ctest --output-on-failure -j $JOBS_NUMBER
  only:
    - merge_requests

clang-release-arch:
  stage: build
  image: $ARCH_IMAGE
  script:
    - cmake -B.build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Release -DQT_QMAKE_EXECUTABLE=qmake
    - cmake --build .build -j $JOBS_NUMBER
    - pushd .build && ctest --output-on-failure -j $JOBS_NUMBER
  only:
    - merge_requests

clang-debug-arch:
  stage: build
  image: $ARCH_IMAGE
  script:
    - cmake -B.build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Debug -DQT_QMAKE_EXECUTABLE=qmake
    - cmake --build .build -j $JOBS_NUMBER
    - pushd .build && ctest --output-on-failure -j $JOBS_NUMBER
  only:
    - merge_requests

gcc-release-debian:
  stage: build
  image: $DEB_IMAGE
  script:
    - cmake -B.build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DQT_QMAKE_EXECUTABLE=qmake
    - cmake --build .build -j $JOBS_NUMBER
    - pushd .build && ctest --output-on-failure -j $JOBS_NUMBER
  only:
    - merge_requests

gcc-debug-astra:
  stage: build
  image: $ASTRA_IMAGE
  script:
    - cmake -B.build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=Debug
    - cmake --build .build -j $JOBS_NUMBER
    - pushd .build && ctest --output-on-failure -j $JOBS_NUMBER
  only:
    - merge_requests

gcc-release-astra:
  stage: build
  image: $ASTRA_IMAGE
  script:
    - cmake -B.build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=Release
    - cmake --build .build -j $JOBS_NUMBER
    - pushd .build && ctest --output-on-failure -j $JOBS_NUMBER
  only:
    - merge_requests

mingw-release-debian-mxe:
  stage: build
  image: $DEB_MXE_IMAGE
  script:
    - mkdir -p .build
    - pushd .build
    - MXE_ROOT="/opt/mxe"
    - PATH="$MXE_ROOT/usr/bin:/usr/local/bin:/usr/bin:/bin"
    - WINEPATH="$MXE_ROOT/usr/i686-w64-mingw32.shared/bin;$MXE_ROOT/usr/i686-w64-mingw32.shared/qt5/bin/;$MXE_ROOT/mxe/usr/i686-w64-mingw32.shared/qt5/plugins/;$MXE_ROOT/usr/i686-w64-mingw32.shared/lib/"
    - >
      i686-w64-mingw32.shared-cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_CROSSCOMPILING_EMULATOR=wine \
        -DCMAKE_INSTALL_PREFIX="" \
        -DINSTALL_PREFIX=".." \
        -DCONFIG_PATH="../etc" \
        -DINITD_PATH="../etc" \
        -DCACHE_PATH="../cache" \
        -DSHARED_PATH="../share" \
        -DPLUGIN_PATH="../lib/plugins" \
        -DHELP_PATH="../doc" \
        -DTRANSLATION_PATH="../translations" \
        -DGTEST_OPTIONS="-Dgtest_disable_pthreads:BOOL=ON" ../
    - make -j $JOBS_NUMBER
    - make DESTDIR=$(pwd) install
    - WINEPATH="$WINEPATH;$(pwd)/bin;$(pwd)/lib"
    - ctest --output-on-failure -j $JOBS_NUMBER
  only:
    - merge_requests
  tags:
    - local
