services:

  app:
    container_name: dds-provider
    image: ${CI_REGISTRY_IMAGE}:${IMAGE_TAG}
    command: [./dds-provider, -debug]
    ports:
      - "19080:19080"
    environment:
      - LISTEN
      - LOG_LEVEL

      - DB_PG_NAME
      - DB_PG_USER
      - DB_PG_PASS
      - DB_PG_HOST
      - DB_PG_PORT

      - BULAT_DEVICES

