- name: Deny in traffic
  ufw:
    policy: deny
    direction: incoming

- name: Allow out traffic
  ufw:
    policy: allow
    direction: outgoing

- name: Open and limit ssh access and enable UFW
  ufw:
    state: enabled
    rule: limit
    port: ssh
    proto: tcp

- name: Open public ports
  ufw:
    rule: allow
    port: "{{ item.0 }}"
    proto: "{{ item.1 }}"
  loop:
    - [ "19080:19081", tcp ] # Provider API
    - [ "8080", tcp ] # Deploy API
