# @file
# @brief deb specific CPack configuration
#
# Debian package
#

macro(setupDeb)
    set(CPACK_DEBIAN_PACKAGE_NAME           "${PACKAGE_NAME}")
    set(CPACK_DEBIAN_PACKAGE_VERSION        "${CPACK_PACKAGE_VERSION}")
    set(CPACK_DEBIAN_PACKAGE_MAINTAINER     "${CPACK_PACKAGE_CONTACT}")
    set(CPACK_DEBIAN_PACKAGE_DESCRIPTION    "${CPACK_PACKAGE_DESCRIPTION_SUMMARY}")
    set(CPACK_DEBIAN_PACKAGE_SECTION        "misc")
    set(CPACK_DEBIAN_PACKAGE_PRIORITY       "optional")
    set(CPACK_DEB_COMPONENT_INSTALL         "${PACK_COMPONENT_INSTALL}")
    list(APPEND CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${META_PRE_INSTALL_SCRIPT_FILE_OUTPUT}")
    list(APPEND CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${META_PRE_UNINSTALL_SCRIPT_FILE_OUTPUT}")
    list(APPEND CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${META_POST_INSTALL_SCRIPT_FILE_OUTPUT}")
    list(APPEND CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${META_POST_UNINSTALL_SCRIPT_FILE_OUTPUT}")
    list(APPEND CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${META_PRE_UPGRADE_SCRIPT_FILE_OUTPUT}")
    list(APPEND CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${META_POST_UPGRADE_SCRIPT_FILE_OUTPUT}")
endmacro()
