# @file
# @brief rpm specific CPack configuration
#
# RPM package
#

macro(setupRpm)
    set(CPACK_RPM_PACKAGE_NAME                  "${PACKAGE_NAME}")
    set(CPACK_RPM_PACKAGE_VERSION               "${VERSION}")
    set(CPACK_RPM_PACKAGE_RELEASE               1)
    set(CPACK_RPM_PACKAGE_REQUIRES              "")
    set(CPACK_RPM_PACKAGE_PROVIDES              "")
    set(CPACK_RPM_PACKAGE_VENDOR                "${CPACK_PACKAGE_VENDOR}")
    set(CPACK_RPM_PACKAGE_LICENSE               "MIT")
    set(CPACK_RPM_PACKAGE_SUMMARY               "${CPACK_PACKAGE_DESCRIPTION_SUMMARY}")
    set(CPACK_RPM_PACKAGE_DESCRIPTION           "")
    set(CPACK_RPM_PACKAGE_GROUP                 "unknown")

    set(CPACK_RPM_COMPONENT_INSTALL             "${PACK_COMPONENT_INSTALL}")
    set(CPACK_RPM_PRE_INSTALL_SCRIPT_FILE       "${META_PRE_INSTALL_SCRIPT_FILE_OUTPUT}")
    set(CPACK_RPM_PRE_UNINSTALL_SCRIPT_FILE     "${META_PRE_UNINSTALL_SCRIPT_FILE_OUTPUT}")
    set(CPACK_RPM_POST_INSTALL_SCRIPT_FILE      "${META_POST_INSTALL_SCRIPT_FILE_OUTPUT}")
    set(CPACK_RPM_POST_UNINSTALL_SCRIPT_FILE    "${META_POST_UNINSTALL_SCRIPT_FILE_OUTPUT}")

    set(CPACK_SET_DESTDIR                       OFF)
    set(CPACK_RPM_PACKAGE_RELOCATABLE           OFF)
    set(CPACK_RPM_DEBUGINFO_PACKAGE             OFF)
    set(CPACK_RPM_DEBUGINFO_SINGLE_PACKAGE      OFF)

    set(CPACK_RPM_DEBUGINFO_FILE_NAME "${PACKAGE_NAME}-debuginfo_${CPACK_PACKAGE_VERSION}_${CMAKE_SYSTEM_PROCESSOR}.rpm")
endmacro()
