- hosts: all
  tasks:
    - include_role: name=backup tasks_from=rollback-info
    - include_role: name=backup tasks_from=rollback-db
    - include_role: name=services
  become: true
  gather_facts: no
