Vagrant.configure("2") do |config|

  if ENV['OS'] == 'ubuntu'
    config.vm.box = "bento/ubuntu-24.04"
  else
    # https://registry.astralinux.ru/latest/descriptions/local/vagrant/#descriptions-vagrant-boxes
    config.vm.box = "alse-base/1.8.1uu1"
    config.vm.box_url = "https://registry.astralinux.ru/vagrant/alse-base%2F1.8.1uu1"
    config.vm.guest = :debian
  end

  config.vm.define "tamerlan-dev" do |host|
    host.vm.network :private_network, ip: "192.168.56.101"
    host.vm.provider "virtualbox" do |v|
      v.memory = 3000
      v.cpus = 3
    end
  end

  config.vm.disk :disk, primary: true, size: "30GB"

  config.vm.synced_folder "..", "/vagrant", type: "virtualbox", automount: true

  config.vm.synced_folder "../configs/dev-vm", "/var/opt/dds/configs", type: "virtualbox", automount: true
  config.vm.synced_folder "../../dds-local-env/.devdata/control/firmware", "/var/opt/dds/control/firmware", type: "virtualbox", automount: true
  config.vm.synced_folder "../../dds-local-env/.devdata/logs", "/var/opt/dds/logs", owner: "root", group: "root", type: "virtualbox", automount: true

  config.vm.synced_folder ENV['HOME'], ENV['HOME'], mount_options: ["dmode=777", "fmode=666"], type: "virtualbox", automount: true

  config.vm.provision "shell", inline: <<-SCRIPT
    CACHE_PATH=/vagrant/provision/.vagrant/mycache
    mkdir -p $CACHE_PATH
    create_symlink() {
      mkdir -p $CACHE_PATH/$1
      mkdir -p $(dirname $2)
      [[ -e $2 ]] && rm -rf $2
      ln -sf $CACHE_PATH/$1 $2
      echo "Created symlink $2 to $CACHE_PATH/$1"
    }

    create_symlink apt /var/cache/apt/archives
#     create_symlink bin /var/cache/bin

    apt install -y parted

    parted /dev/sda ---pretend-input-tty "resizepart 1 yes 100% p"
    resize2fs /dev/sda1

    apt-get update
    apt-get install -y docker.io

    usermod -aG docker vagrant

    # HACK: in order to start systemd-timesyncd service
    mv /usr/sbin/VBoxService /usr/sbin/VBoxService1
  SCRIPT
end
